spring:
  datasource:
    url: jdbc:mysql://192.168.55.151:3306/subway?serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: masterpw
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
